// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDubi6Wsbe0PwpWaMwy9yaEkH5LUbXRlw',
    appId: '1:401426098765:web:9ebcaef314c7bc7aa00a04',
    messagingSenderId: '401426098765',
    projectId: 'taskey-app-fc3ad',
    authDomain: 'taskey-app-fc3ad.firebaseapp.com',
    storageBucket: 'taskey-app-fc3ad.appspot.com',
    measurementId: 'G-GL1G6HKPR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDdwFwAZzjKVEbm-QbVYtBTpxY0m9i9Oo',
    appId: '1:401426098765:android:9a887ee2527c7552a00a04',
    messagingSenderId: '401426098765',
    projectId: 'taskey-app-fc3ad',
    storageBucket: 'taskey-app-fc3ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-eOMWqJpzZ_o10N28-Zjx9eN2eP-mbI',
    appId: '1:401426098765:ios:44a13716076e92ada00a04',
    messagingSenderId: '401426098765',
    projectId: 'taskey-app-fc3ad',
    storageBucket: 'taskey-app-fc3ad.appspot.com',
    iosBundleId: 'com.example.taskeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-eOMWqJpzZ_o10N28-Zjx9eN2eP-mbI',
    appId: '1:401426098765:ios:44a13716076e92ada00a04',
    messagingSenderId: '401426098765',
    projectId: 'taskey-app-fc3ad',
    storageBucket: 'taskey-app-fc3ad.appspot.com',
    iosBundleId: 'com.example.taskeyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDubi6Wsbe0PwpWaMwy9yaEkH5LUbXRlw',
    appId: '1:401426098765:web:56960473705ae7c1a00a04',
    messagingSenderId: '401426098765',
    projectId: 'taskey-app-fc3ad',
    authDomain: 'taskey-app-fc3ad.firebaseapp.com',
    storageBucket: 'taskey-app-fc3ad.appspot.com',
    measurementId: 'G-QL0WRCBFEC',
  );
}
